# Site settings
title: Sau-Chin Chen
email: pmsp96@gmail.com
description: > # this means to ignore newlines until "baseurl:" Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  This website is hosted by Sau-Chin Chen. You can check the source codes
  at my github page.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scchen.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: SCgeeker

#production_url: http://schen.com

#source: ./_source
destination: ./_site

# Build settings
## highlighter: pygments
markdown: Kramdown
#markdown_ext: markdown
kramdown:
  math_engine: mathjax
##  extensions:
##    - autolink
##    - footnotes
##    - smart

#exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
#auto: true
#pygments: true
  
# Other options
### Disable permalink, blog posts are available
permalink: blog/:year/:month/:title.html
#relative_permalinks: false
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
